project_id = "zckjqudeoodfxikhdfvh"

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.translate-batch]
verify_jwt = false

[functions.elevenlabs-clone-voice]
verify_jwt = false

[functions.elevenlabs-tts-lari]
verify_jwt = false

[functions.elevenlabs-add-samples]
verify_jwt = false

[functions.translate-lari]
verify_jwt = false

[functions.elevenlabs-tts-general]
verify_jwt = false

[functions.elevenlabs-stt]
verify_jwt = false

[functions.lessons-data]
verify_jwt = false

[functions.mbuta-matondo]
verify_jwt = false

[functions.whisper-stt]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true
